from PyQt5.QtWidgets import (QWidget, QApplication, QLabel, QLineEdit, QPushButton)
from PyQt5.QtCore import *
from PyQt5.QtGui import *
import sqlite3

class DB_Table_Input(QWidget):
    def __init__(self):
        super().__init__()

        # Connect with Database
        self.databaseName = 'ark_db'
        self.databaseName = f'{self.databaseName}.db'
        self.tableName = 'ark_table'
        self.connectDB()
        self.createTable()

        ######################################################
        # new db
        ######################################################


    def connectDB(self):
        """ This creates a databse if one has not been created, or
        connects to an already existing one if one exists."""

        ######################################################
        # new db
        ######################################################

        self.conn = sqlite3.connect(self.databaseName)
        self.c = self.conn.cursor()
        self.conn.commit()

        print('database created')

    def createTable(self):
        """ This function creates a new table
        is one has not been created"""

        self.field1 = 'FileNo'
        self.field1Type = 'TEXT'
        self.field2 = 'CoName'
        self.field2Type = 'TEXT'
        self.field3 = 'CoOldName'
        self.field3Type = 'TEXT'
        self.field4 = 'RegNO'
        self.field4Type = 'TEXT'
        self.field5 = 'DateOfChange'
        self.field5Type = 'TEXT'
        self.field6 = 'IncDate'
        self.field6Type = 'TEXT'
        self.field7 = 'CoStatus'
        self.field7Type = 'TEXT'
        self.field8 = 'RegisteredAdd'
        self.field8Type = 'TEXT'
        self.field9 = 'BusinessAdd'
        self.field9Type = 'TEXT'
        self.field10 = 'NatureOfBusiness'
        self.field10Type = 'TEXT'
        self.field11 = 'PaidUpCapital'
        self.field11Type = 'TEXT'
        self.field12 = 'Member1'
        self.field12Type = 'TEXT'
        self.field13 = 'Member1_Shares'
        self.field13Type = 'TEXT'
        self.field14 = 'Member2'
        self.field14Type = 'TEXT'
        self.field15 = 'Member2_Shares'
        self.field15Type = 'TEXT'
        self.field16 = 'Member3'
        self.field16Type = 'TEXT'
        self.field17 = 'Member3_Shares'
        self.field17Type = 'TEXT'
        self.field18 = 'Member4'
        self.field18Type = 'TEXT'
        self.field19 = 'Member4_Shares'
        self.field19Type = 'TEXT'
        self.field20 = 'Member5'
        self.field20Type = 'TEXT'
        self.field21 = 'Member5_Shares'
        self.field21Type = 'TEXT'
        self.field22 = 'Director1'
        self.field22Type = 'TEXT'
        self.field23 = 'Director2'
        self.field23Type = 'TEXT'
        self.field24 = 'Director3'
        self.field24Type = 'TEXT'
        self.field25 = 'Director4'
        self.field25Type = 'TEXT'
        self.field26 = 'Director5'
        self.field26Type = 'TEXT'

        # ----------------------------------------------Secretaries -------------------------------------------------
        self.field27 = 'Secretaries1'
        self.field27Type = 'TEXT'
        self.field28 = 'Sec1_Appointed_Date'
        self.field28Type = 'TEXT'
        self.field29 = 'Sec1_Resigned_Date'
        self.field29Type = 'TEXT'
        self.field30 = 'Sec1_Vacated_Date'
        self.field30Type = 'TEXT'

        self.field31 = 'Secretaries2'
        self.field31Type = 'TEXT'
        self.field32 = 'Sec2_Appointed_Date'
        self.field32Type = 'TEXT'
        self.field33 = 'Sec2_Resigned_Date'
        self.field33Type = 'TEXT'
        self.field34 = 'Sec2_Vacated_Date'
        self.field34Type = 'TEXT'
        # ----------------------------------------------Contact Persons & Prepared -------------------------------------------------

        self.field35 = 'ContactPerson'
        self.field35Type = 'TEXT'
        self.field36 = 'ContactPersonTel'
        self.field36Type = 'TEXT'
        self.field37 = 'ContactPersonEmail'
        self.field37Type = 'TEXT'

        self.field38 = 'PreparedBy'
        self.field38Type = 'TEXT'
        self.field39 = 'PreparedDate'
        self.field39Type = 'TEXT'
        self.field40 = 'ScannedBy'
        self.field40Type = 'TEXT'
        self.field41 = 'ScannedDate'
        self.field41Type = 'TEXT'
        self.field42 = 'CheckedBy'
        self.field42Type = 'TEXT'
        self.field43 = 'CheckedDate'
        self.field43Type = 'TEXT'

        #---------------------------------------Files-----------------------

        self.field44 = '_Directors_Circular'
        self.field44Type = 'TEXT'
        self.field45 = '_Members_Meeting'
        self.field45Type = 'TEXT'
        self.field46 = '_Register'
        self.field46Type = 'TEXT'
        self.field47 = '_Share_Certificate'
        self.field47Type = 'TEXT'
        self.field48 = '_Summary'
        self.field48Type = 'TEXT'
        self.field49 = '_Checklist'
        self.field49Type = 'TEXT'
        self.field50 = '_Correspondence'
        self.field50Type = 'TEXT'
        self.field51 = '_Bill_SOA'
        self.field51Type = 'TEXT'
        self.field52 = '_SSM_Receipt'
        self.field52Type = 'TEXT'
        self.field53 = '_Application_Of_Reg'
        self.field53Type = 'TEXT'
        self.field54 = '_Availability_Names_Reg'
        self.field54Type = 'TEXT'

        self.field55 = '_Application_Change_Name'
        self.field55Type = 'TEXT'
        self.field56 = '_Lodgement_Constitution'
        self.field56Type = 'TEXT'
        self.field57 = '_Notify_Alteration_Amendment'
        self.field57Type = 'TEXT'
        self.field58 = '_Change_Reg_Add'
        self.field58Type = 'TEXT'
        self.field59 = '_Not_at_Reg_Add'
        self.field59Type = 'TEXT'
        self.field60 = '_Change_Add_Reg_Are_Kept'
        self.field60Type = 'TEXT'
        self.field61 = '_Change_Reg_of_Members'
        self.field61Type = 'TEXT'
        self.field62 = '_Change_Reg_Dir_Mgr_Sec'
        self.field62Type = 'TEXT'
        self.field63 = '_Annual_Return_of_Company'
        self.field63Type = 'TEXT'
        self.field64 = '_Approval_for_Allotment'
        self.field64Type = 'TEXT'
        self.field65 = '_Return_for_Allotment'
        self.field65Type = 'TEXT'
        self.field66 = '_Variation_Class_of_Rights'
        self.field66Type = 'TEXT'
        self.field67 = '_Instrument_of_Transfer'
        self.field67Type = 'TEXT'
        self.field68 = '_Solvency_Statement'
        self.field68Type = 'TEXT'
        self.field69 = '_Declaration_Appnt_as_Director'
        self.field69Type = 'TEXT'
        self.field70 = '_Notice_Contract_Serv_Director'
        self.field70Type = 'TEXT'
        self.field71 = '_Declaration_Appnt_as_Secretary'
        self.field71Type = 'TEXT'
        self.field72 = '_Vacate_Office_of_Secretary'
        self.field72Type = 'TEXT'
        self.field73 = '_Dec_by_Sec_to_Cease_Off'
        self.field73Type = 'TEXT'
        self.field74 = '_Reg_to_Act_as_Sec'
        self.field74Type = 'TEXT'
        self.field75 = '_Diff_Accounting_Periods'
        self.field75Type = 'TEXT'
        self.field76 = '_EOT_Financial_Statements'
        self.field76Type = 'TEXT'
        self.field77 = '_Exempt_Private_Company'
        self.field77Type = 'TEXT'
        self.field78 = '_Lodge_with_Charge'
        self.field78Type = 'TEXT'
        self.field79 = '_Series_of_Debentures'
        self.field79Type = 'TEXT'
        self.field80 = '_Assignment_of_Charge'
        self.field80Type = 'TEXT'
        self.field81 = '_Variations_Terms_of_Change'
        self.field81Type = 'TEXT'
        self.field82 = '_Property_Undertaking_Memo'
        self.field82Type = 'TEXT'
        self.field83 = '_Memo_Satisfaction_Reg_Charge'
        self.field83Type = 'TEXT'
        self.field84 = '_Dec_Verifying_Memo'
        self.field84Type = 'TEXT'
        self.field85 = '_Satisfaction_of_Charge'
        self.field85Type = 'TEXT'
        self.field86 = '_Strike_of_Company'
        self.field86Type = 'TEXT'
        self.field87 = '_Object_Striking_of_Company'
        self.field87Type = 'TEXT'
        self.field88 = '_Withdraw_Striking_of_Company'
        self.field88Type = 'TEXT'
        self.field89 = '_Change_in_Bus_Add_or_Nat_of_Bus'
        self.field89Type = 'TEXT'
        self.field90 = '_File_47'
        self.field90Type = 'TEXT'
        self.field91 = '_Temporary_Folder'
        self.field91Type = 'TEXT'

        self.c.execute(f'CREATE TABLE IF NOT EXISTS {self.tableName} ({self.field1} {self.field1Type} primary key,'
                       f'{self.field2} {self.field2Type},'
                       f'{self.field3} {self.field3Type},'
                       f'{self.field4} {self.field4Type},'
                       f'{self.field5} {self.field5Type},'
                       f'{self.field6} {self.field6Type},'
                       f'{self.field7} {self.field7Type},'
                       f'{self.field8} {self.field8Type},'
                       f'{self.field9} {self.field9Type},'
                       f'{self.field10} {self.field10Type},'
                       f'{self.field11} {self.field11Type},'
                       f'{self.field12} {self.field12Type},'
                       f'{self.field13} {self.field13Type},'
                       f'{self.field14} {self.field14Type},'
                       f'{self.field15} {self.field15Type},'
                       f'{self.field16} {self.field16Type},'
                       f'{self.field17} {self.field17Type},'
                       f'{self.field18} {self.field18Type},'
                       f'{self.field19} {self.field19Type},'
                       f'{self.field20} {self.field20Type},'
                       f'{self.field21} {self.field21Type},'
                       f'{self.field22} {self.field22Type},'
                       f'{self.field23} {self.field23Type},'
                       f'{self.field24} {self.field24Type},'
                       f'{self.field25} {self.field25Type},'
                       f'{self.field26} {self.field26Type},'
                       f'{self.field27} {self.field27Type},'
                       f'{self.field28} {self.field28Type},'
                       f'{self.field29} {self.field29Type},'
                       f'{self.field30} {self.field30Type},'
                       f'{self.field31} {self.field31Type},'
                       f'{self.field32} {self.field32Type},'
                       f'{self.field33} {self.field33Type},'
                       f'{self.field34} {self.field34Type},'
                       f'{self.field35} {self.field35Type},'
                       f'{self.field36} {self.field36Type},'
                       f'{self.field37} {self.field37Type},'
                       f'{self.field38} {self.field38Type},'
                       f'{self.field39} {self.field39Type},'
                       f'{self.field40} {self.field40Type},'
                       f'{self.field41} {self.field41Type},'
                       f'{self.field42} {self.field42Type},'
                       f'{self.field43} {self.field43Type},'
                       f'{self.field44} {self.field44Type},'
                       f'{self.field45} {self.field45Type},'
                       f'{self.field46} {self.field46Type},'
                       f'{self.field47} {self.field47Type},'
                       f'{self.field48} {self.field48Type},'
                       f'{self.field49} {self.field49Type},'
                       f'{self.field50} {self.field50Type},'
                       f'{self.field51} {self.field51Type},'
                       f'{self.field52} {self.field52Type},'
                       f'{self.field53} {self.field53Type},'
                       f'{self.field54} {self.field54Type},'
                       f'{self.field55} {self.field55Type},'
                       f'{self.field56} {self.field56Type},'
                       f'{self.field57} {self.field57Type},'
                       f'{self.field58} {self.field58Type},'
                       f'{self.field59} {self.field59Type},'
                       f'{self.field60} {self.field60Type},'
                       f'{self.field61} {self.field61Type},'
                       f'{self.field62} {self.field62Type},'
                       f'{self.field63} {self.field63Type},'
                       f'{self.field64} {self.field64Type},'
                       f'{self.field65} {self.field65Type},'
                       f'{self.field66} {self.field66Type},'
                       f'{self.field67} {self.field67Type},'
                       f'{self.field68} {self.field68Type},'
                       f'{self.field69} {self.field69Type},'
                       f'{self.field70} {self.field70Type},'
                       f'{self.field71} {self.field71Type},'
                       f'{self.field72} {self.field72Type},'
                       f'{self.field73} {self.field73Type},'
                       f'{self.field74} {self.field74Type},'
                       f'{self.field75} {self.field75Type},'
                       f'{self.field76} {self.field76Type},'
                       f'{self.field77} {self.field77Type},'
                       f'{self.field78} {self.field78Type},'
                       f'{self.field79} {self.field79Type},'
                       f'{self.field80} {self.field80Type},'
                       f'{self.field81} {self.field81Type},'
                       f'{self.field82} {self.field82Type},'
                       f'{self.field83} {self.field83Type},'
                       f'{self.field84} {self.field84Type},'
                       f'{self.field85} {self.field85Type},'
                       f'{self.field86} {self.field86Type},'
                       f'{self.field87} {self.field87Type},'
                       f'{self.field88} {self.field88Type},'
                       f'{self.field89} {self.field89Type},'
                       f'{self.field90} {self.field90Type},'
                       f'{self.field91} {self.field91Type})')

        self.conn.commit()
        print('Table Created')